language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
env:
  global:
  - secure: UA7NuRJBHBrtNULAWB6YFwVkNB02dHDtkxaQDHFRnuW4KlDL6AGqdLGpiYhDFiGW1MZAoNHv7nEXkgTARoZhWWnd6Ebtq9naPRa5cYREPbm4yU4/NCgYoLuhVv7h63dE6ovQxCXYerXAeXBvzMZdDfc3eXtlgPdyR6Z30jwTw/eq0O30KSGAK1EMZQiJI0OlbWvIKRrELEBM86MaaqpbDUgiOB1/wbWULtt1QNxyY7OdGpPvIjpIbXfIebu4Jfw2taswBWquU/bvayG4kPLTuYx2mVMcVuS7Z7GCu7dHpqoIF24v8cKTDdf1JSDShgTM71IFd2lJTEjilB0x795Raf/qf7m+77NOEry4IO8qMZ0xEJHQC+kFfUpyKZFZiQ16mpNLgk7w9/NQjAHQDYiRpRgRrXtjoKP5nAin3yZvWvtNY90HrRyIq5EtAqOaUyyTHb5k+k/+Im3dAaMavAD8r9DVgg3Pe1+jiV9o509GxYMbap7ArF3vQC8E/t90+0abe3uvtMjMjB/wGg6xug8UWEqu7LilaUl1q///XL8hBG424aH1GbibXyOv1wgHqM1hK9iSOGDO/hKLEj/SAaqtUEzrZe9jVHLpiIiAxFl2CqVfvM3iBsBaKNFnKZBMgWqqDDVsMRpUmzmb2LQxSykyDyH8moNniFvNfIBsVWLRJLQ=
  - secure: JcNMT8v5kMUTxCdknqL6qNzDbCX5iIahPo/TlWYgIw5CWhvn0+GKdDc2bK/00YM6a6pQ4dJ2qUvlwqeen0v4Nmqdd0M+BSwhWNJGF7VJxTikhdmUKPdp2AknufysSvsnvl/zMPzeFkNgYoMluvua8yWYgIudwjOuMkWnDdO/kEQchtoH2JwAt7FDCvTveRBN3lSApKS++ZujNE/2qsqiI+fCpugAxZAVBIQg4YxP4yHW77uw9PmuZBR3vzNiIbDxToWQL4GlasByII552axvlPBgHQ/6AYlFyBLX0H06v1no5nO2A3gWAPqjz+tDU/5qjIbUYXDrXB1TRy4HVR90oRBWYtuR2uPWf6dbqJU6l17+3d6bOpU/QP36bDsRVcdFSeCXxiFEmyE0vkxVfM6Vh+EqcnJTZdBr20xIsoZlgrAkP0c6mvZf2MxJ7OoJ/YCml15/2WHeRfyNdsz3o4gCtJQp2aXDgtwCNq1aZjCAD5sHKjWMV5t87B4Rq2wuKcBtxhTJrGCYDNeguqMFJ3ZCHt4+GFNAubRTtEYboKmlnHNiKiewPXlEYKjKZxi2Zt32bmV4pb/FyWGf9MpowMw9qN8XaqgNhfHDTp9opr4VOc5dSrnke/5vGvU4l35+Nq5LMqWF2E/L+K/lMoVDOn83HgU6n8mGxbiXVeyt2ZRxQHg=
